---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: pydantic_analysis_agent
build:
  artifacts:
    - image: fahim03/streamlit_app
      context: ./services/streamlit_app
    - image: fahim03/agent_app
      context: ./services/agent_app
    - image: fahim03/sandbox_image
      context: ./services/sandbox_template_image
  local:
    useDockerCLI: true
    useBuildkit: true

manifests:
  rawYaml:
    # - https://github.com/kubernetes-sigs/agent-sandbox/releases/latest/download/sandbox-with-extensions.yaml
    - ./manifests/db/namespace.yaml
    - ./manifests/gateway/gateway.yaml
    - ./manifests/gateway/host_gateway.yaml
  helm:
    releases:
      - name: postgres
        remoteChart: bitnami/postgresql
        namespace: postgres-helm
        valuesFiles:
          - ./manifests/db/secret_values.yaml
  kustomize:
    paths:
      - ./manifests/agent_app
      - ./manifests/streamlit_app
      - ./manifests/jupyter_sandbox
