---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bucket-deploy
  labels:
    app: bucket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bucket-pod
  template:
    metadata:
      labels:
        app: bucket-pod
    spec:
      containers:
        - name: bucket-cont
          image: fahim03/bucket_service:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: bucket-config
            - secretRef:
                name: bucket-secret
          # env:
          #   - name: AWS_ENDPOINT_URL
          #     valueFrom:
          #       configMapKeyRef:
          #         name: bucket-config
          #         key: AWS_ENDPOINT_URL
          #   - name: AWS_DEFAULT_REGION
          #     valueFrom:
          #       configMapKeyRef:
          #         name: bucket-config
          #         key: AWS_DEFAULT_REGION
          #   - name: AWS_ACCESS_KEY_ID
          #     valueFrom:
          #       secretKeyRef:
          #         name: bucket-secret
          #         key: AWS_ACCESS_KEY_ID
          #   - name: AWS_SECRET_ACCESS_KEY
          #     valueFrom:
          #       secretKeyRef:
          #         name: bucket-secret
          #         key: AWS_ACCESS_KEY_ID
