OPENAI_BASE_URL=http://dockerhost:8080/v1
OPENAI_MODEL_NAME=Qwen3.8-27b
POSTGRES_HOSTNAME=postgresql.postgres-helm
POSTGRES_PORT=5432
POSTGRES_USER=myuser
POSTGRES_DB=mydb
CONTEXT_LENGTH=98304
LANGFUSE_BASE_URL=http://langfuse-web.langfuse:3000
