---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-deploy
  labels:
    app: bucket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit-pod
  template:
    metadata:
      labels:
        app: streamlit-pod
    spec:
      containers:
        - name: streamlit-cont
          image: fahim03/streamlit_app:latest
          ports:
            - containerPort: 8501
          readinessProbe:
            httpGet:
              path: "/_stcore/health"
              port: 8501
            initialDelaySeconds: 0
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: "/_stcore/health"
              port: 8501
          envFrom:
            - configMapRef:
                name: streamlit-config
            # - secretRef:
            #     name: streamlit-secret
