---
configMapGenerator:
  - name: streamlit-config
    envs:
      - ./application.properties

# secretGenerator:
#   - name: streamlit-secret
#     envs:
#       - ./.env

resources:
  - deploy.yaml
  - service.yaml
